# Generated by Django 6.0.4 on 2026-04-23 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexpense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense_tracker_app.addcategory'),
        ),
        migrations.AlterField(
            model_name='addexpense',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
