# Generated by Django 6.0.4 on 2026-04-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker_app', '0002_alter_addexpense_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexpense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('Not Set'), to='expense_tracker_app.addcategory'),
        ),
    ]
