# Generated by Django 6.0.4 on 2026-04-25 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker_app', '0003_alter_addexpense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexpense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense_tracker_app.addcategory'),
        ),
    ]
