# Generated by Django 6.0.4 on 2026-05-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker_app', '0005_addbudget_addsavings'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbudget',
            name='time_period',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='daily', max_length=70),
        ),
        migrations.AddField(
            model_name='addsavings',
            name='time_period',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='daily', max_length=70),
        ),
    ]
