# Generated by Django 6.0.4 on 2026-05-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker_app', '0006_addbudget_time_period_addsavings_time_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addbudget',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='addsavings',
            name='amount',
        ),
        migrations.AddField(
            model_name='addbudget',
            name='budget_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='addsavings',
            name='savings_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
