# Generated by Django 6.0.4 on 2026-05-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker_app', '0007_remove_addbudget_amount_remove_addsavings_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addbudget',
            name='budget_amount',
        ),
        migrations.RemoveField(
            model_name='addsavings',
            name='savings_amount',
        ),
        migrations.AddField(
            model_name='addbudget',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addsavings',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
