# Generated by Django 6.0.4 on 2026-05-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker_app', '0008_remove_addbudget_budget_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addbudget',
            name='date',
        ),
        migrations.RemoveField(
            model_name='addbudget',
            name='description',
        ),
        migrations.RemoveField(
            model_name='addbudget',
            name='time_period',
        ),
        migrations.AddField(
            model_name='addbudget',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addbudget',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AddSavings',
        ),
    ]
